FROM golang:1.22.4

WORKDIR /app

COPY . .

RUN go install github.com/air-verse/air@latest

# Copy the Go module files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code into the container
COPY . .

EXPOSE 8000

# Run the application with Air for hot reloading
CMD ["air"]
