networks:
  cassandra-net:
  chat-system:

volumes:
  cassandra_seed_data_1:
  cassandra_node1_data:
  cassandra_node2_data:

services:
  cassandra-seed-1:
    image: cassandra:latest
    container_name: cassandra-seed-1
    ports:
      - "7000:7000" # JMX port
      - "9042:9042" # CQL port
    environment:
      - CASSANDRA_CLUSTER_NAME=chat-app
      - CASSANDRA_LISTEN_ADDRESS=auto
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-seed-1
    volumes:
      - cassandra_seed_data_1:/var/lib/cassandra
    networks:
      - cassandra-net
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 40s

  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    ports:
      - "9043:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=chat-app
      - CASSANDRA_LISTEN_ADDRESS=auto
      - CASSANDRA_SEEDS=cassandra-seed-1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node1
    volumes:
      - cassandra_node1_data:/var/lib/cassandra
    depends_on:
      - cassandra-seed-1
    networks:
      - cassandra-net
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 40s

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - chat-system

  wait-for-it:
    image: willwill/wait-for-it
    container_name: wait-for-it
    depends_on:
      cassandra-node1:
        condition: service_healthy
      redis:
        condition: service_healthy
    command:
      [
        "cassandra-node1:9043",
        "redis:6379",
        "--",
        "echo",
        "All services are up and healthy",
      ]
    networks:
      - chat-system
      - cassandra-net

  chat-service:
    image: cme/chat-service
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: chat-service
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app # Mount the source code directory into the container for hot reload
    depends_on:
      - wait-for-it
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8000/api/v1/health || exit 1"]
      interval: 30s
      timeout: 600s
      retries: 20
      start_period: 40s
    networks:
      - chat-system
      - cassandra-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      chat-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/api/v1/health || exit 1"]
      interval: 30s
      timeout: 600s
      retries: 20
      start_period: 40s
    networks:
      - chat-system
